import { test, expect } from '@playwright/test'

test('Segurados e Oportunidades persistem na interface original', async ({ page }) => {
  const baseUrl = process.env.WASSIS_E2E_URL ?? 'http://localhost:3011'
  if (!['localhost', '127.0.0.1'].includes(new URL(baseUrl).hostname)) throw new Error('Somente ambiente descartável local.')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(baseUrl)
  await page.getByPlaceholder('seu@email.com').fill('user0@example.invalid')
  await page.getByPlaceholder('••••••••', { exact: true }).fill('local-integration-fixture-password')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Segurados', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Encolher menu' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Financeiro', exact: true })).toHaveAttribute('aria-disabled', 'true')
  const name = `Fixture original ${Date.now()}`
  const digits = String(Date.now()).slice(-9).split('').map(Number)
  for (const length of [9, 10]) { const sum = digits.reduce((total, digit, index) => total + digit * (length + 1 - index), 0); const value = (sum * 10) % 11; digits.push(value === 10 ? 0 : value) }
  await page.getByRole('button', { name: 'Novo Segurado', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByPlaceholder('Ex: Maria da Silva').fill(name)
  await dialog.getByPlaceholder('000.000.000-00').fill(digits.join(''))
  await dialog.getByPlaceholder('email@exemplo.com').fill('fixture@example.invalid')
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Criar segurado' }).click()
  await expect(page).toHaveURL(/\/segurados\/[^/?]+$/)
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Segurados', exact: true }).click()
  await page.getByRole('row').filter({ hasText: name }).getByTitle('Editar cadastro').click()
  await page.getByPlaceholder('Ex: Maria da Silva').fill(`${name} atualizado`)
  await page.getByRole('button', { name: 'Salvar Alterações', exact: true }).click()
  await expect(page.getByText(`${name} atualizado`, { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText(`${name} atualizado`, { exact: true })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('segurados-original-desktop.png'), fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Oportunidades', exact: true }).click()
  await page.getByRole('button', { name: 'Nova oportunidade', exact: true }).click()
  const opportunityName = `Oportunidade ${Date.now()}`
  await page.getByPlaceholder('Ex.: Seguro residencial — apartamento novo').fill(opportunityName)
  await page.getByRole('dialog').getByRole('textbox', { name: /Buscar segurado/i }).fill(`${name} atualizado`)
  await page.getByRole('dialog').getByRole('button').filter({ hasText: `${name} atualizado` }).click()
  await page.getByRole('dialog').getByRole('combobox', { name: /Ramo/i }).selectOption('77777777-7777-7777-7777-777777777777')
  await page.getByRole('button', { name: 'Cadastrar oportunidade', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByText(opportunityName, { exact: true }).click()
  await expect(page.getByRole('heading', { name: opportunityName, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: opportunityName, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Prêmio estimado', { exact: true }).fill('1250.50')
  await page.getByLabel('Fechamento previsto', { exact: true }).fill('2026-10-20')
  await page.getByRole('button', { name: 'Salvar alterações', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Editar Visão geral', exact: true })).toHaveCount(0)
  await page.reload()
  await page.getByRole('button', { name: 'Editar', exact: true }).click()
  await expect(page.getByLabel('Prêmio estimado', { exact: true })).toHaveValue('1250.5')
  await expect(page.getByLabel('Fechamento previsto', { exact: true })).toHaveValue('2026-10-20')
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await page.getByRole('button', { name: 'Marcar como ganha', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar Ganho', exact: true }).click()
  await expect(page.getByText('Ganha', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Ganha', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Tarefas', exact: true }).click()
  await expect(page.getByText('Integração pendente.', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: 'Oportunidades', exact: true }).click()
  await page.getByRole('button', { name: 'Todas', exact: true }).click()
  await page.getByRole('button', { name: 'Exibir lista', exact: true }).click()
  await expect(page.getByText(opportunityName, { exact: true })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('oportunidades-original-lista.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Exibir Kanban', exact: true }).click()
  await expect(page.getByText(opportunityName, { exact: true })).toBeVisible()
  await expect(page.getByText(opportunityName, { exact: true }).locator('..').getByText('20/10/2026', { exact: true })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('oportunidades-original-kanban.png'), fullPage: true, animations: 'disabled' })
  // A new session must refetch instead of reusing data cached by the previous identity.
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await page.getByPlaceholder('seu@email.com').fill('user0@example.invalid')
  await page.getByPlaceholder('••••••••', { exact: true }).fill('local-integration-fixture-password')
  const freshInsured = page.waitForResponse(response => response.request().method() === 'GET' && /\/api\/segurados(?:\?|$)/.test(response.url()))
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await page.getByRole('link', { name: 'Segurados', exact: true }).click()
  expect((await freshInsured).ok()).toBe(true)
  expect(errors).toEqual([])
})
